[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM="xterm-256color"

[font.bold]
family = "mononoki Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "mononoki Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "mononoki Nerd Font Mono"
style = "Italic"

[font.normal]
family = "mononoki Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[scrolling]
history = 100000
multiplier = 3

[window]
opacity = 0.85

[window.padding]
x = 8
y = 8
